CREATE TABLE IF NOT EXISTS todo (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
	created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
	description TEXT NOT NULL,
	completed   BOOL DEFAULT FALSE,
  due_date    DATETIME,
	priority    INTEGER DEFAULT 5 NOT NULL CHECK (priority IN (1, 2, 3, 4, 5)),
	status      TEXT DEFAULT 'pending'
);
